name: Continuous Deployment to GitOps

on:
  workflow_call:
    inputs:
      tag:
        description: Image tag to deploy
        required: true
        type: string
      environment:
        description: Deployment environment (staging or production)
        required: true
        type: string
      apps_dir:
        description: Base directory that contains the applications (e.g., apps)
        required: true
        type: string
      app_name:
        description: Application name to update (e.g., insight-hub)
        required: true
        type: string
    secrets:
      GITOPS_REPO_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  update-gitops:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: Alquimia-ai/infrastructure-gitops
          token: ${{ secrets.GITOPS_REPO_TOKEN }}
          path: gitops
          ref: openshift

      - name: Update image tag in overlay
        shell: bash
        env:
          TAG: ${{ inputs.tag }}
          ENV: ${{ inputs.environment }}
          APPS_DIR: ${{ inputs.apps_dir }}
          APP_NAME: ${{ inputs.app_name }}
        run: |
          set -euo pipefail
          echo "Updating overlay: $ENV with tag: $TAG"
          cd gitops/${APPS_DIR}/${APP_NAME}/overlays/$ENV
          sed -i "s|alquimiaai/${APP_NAME}:.*|alquimiaai/${APP_NAME}:${TAG}|" image-tag-patch.yaml

      - name: Commit and push changes to GitOps
        shell: bash
        env:
          TAG: ${{ inputs.tag }}
          ENV: ${{ inputs.environment }}
          APP_NAME: ${{ inputs.app_name }}
        run: |
          set -euo pipefail
          cd gitops
          git config user.name "GitHub Actions"
          git config user.email "ci@github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Update ${APP_NAME} image tag to ${TAG} for ${ENV}"
          git push origin openshift


