name: mcp-testing

on:
  workflow_call:
    inputs:
      test_file:
        description: "Path to the test file to run"
        required: true
        type: string
      python_version:
        description: "Python version to use"
        required: false
        type: string
        default: "3.12"
      uv_version:
        description: "uv version to use"
        required: false
        type: string
        default: "latest"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: ${{ inputs.uv_version }}

      - name: Install dependencies
        run: uv sync

      - name: Run tests
        run: uv run python ${{ inputs.test_file }}
