name: Determine Tags

on:
  workflow_call:
    inputs:
      ref_name:
        description: "Git reference name"
        required: true
        type: string
    outputs:
      tags:
        description: "Docker tags based on branch"
        value: ${{ jobs.set-tag.outputs.tag }}

jobs:
  set-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set.outputs.tag }}
    steps:
      - id: set
        run: |
          if [[ "${{ inputs.ref_name }}" == "main" ]]; then
            echo "tag=stable" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.ref_name }}" == "develop" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=unknown" >> $GITHUB_OUTPUT
          fi